backend/myproject/core/urls.py
from django.urls import path
from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('dashboard/', v.dashboard, name='dashboard'),
    path('configs/', v.configs, name='configs'),
    path('configs/edit/', v.configs_edit, name='configs_edit'),
]

backend/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('accounts/', include('myproject.accounts.urls')),
    path('api/crm/', include('myproject.crm.urls')),
    # path('crm/', include('myproject.crm.urls')),
    path('financial/', include('myproject.financial.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

backend/myproject/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    address_number = models.IntegerField('número', null=True, blank=True)
    complement = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True


class Document(models.Model):
    cpf = models.CharField(
        'CPF',
        max_length=14,
        unique=True,
        null=True,
        blank=True
    )
    rg = models.CharField('RG', max_length=11, null=True, blank=True)
    cnh = models.CharField('CNH', max_length=20, null=True, blank=True)
    cnpj = models.CharField(
        'CNPJ',
        max_length=18,
        unique=True,
        null=True,
        blank=True
    )
    imun = models.CharField(
        'Inscrição Municipal',
        max_length=12,
        null=True,
        blank=True
    )
    ie = models.CharField(
        'Inscrição Estadual',
        max_length=12,
        null=True,
        blank=True
    )

    class Meta:
        abstract = True


class Active(models.Model):
    active = models.BooleanField('ativo', default=True)

    class Meta:
        abstract = True

backend/myproject/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    ctx = {'mydebug': True}
    return render(request, 'index.html', ctx)


def dashboard(request):
    return render(request, 'dashboard.html')


@login_required
def configs(request):
    return render(request, 'configs.html')


@login_required
def configs_edit(request):
    return render(request, 'configs_edit.html')

backend/myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Regis Santos">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <link rel="shortcut icon" href="https://vuejs.org/images/logo.png">
    <title>CRM {% block title %}{% endblock title %}</title>
    <!-- Icons-->
    <link href="{% static 'css/flag-icon-css/css/flag-icon.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" />
    <!-- jQuery-UI -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- Datatable -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/datatables.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/select/1.2.5/css/select.dataTables.min.css">
    <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui@2.0.0-rc.1/dist/css/coreui.min.css">
    <!-- Main styles for this application-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />
    <link href="{% static 'css/switch.css' %}" rel="stylesheet" />

    <!-- VueJS -->
    <script src="https://unpkg.com/vue"></script>
    <!-- https://github.com/charliekassel/vuejs-datepicker -->
    <script src="https://unpkg.com/vuejs-datepicker"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.min.js"></script>
    <!-- vue2-autocomplete -->
    <!-- <link rel="stylesheet" href="{ static 'vue2-autocomplete.css' %} "> -->
    <!-- <script src="{ static 'vue2-autocomplete.js' %}"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/vuejs-auto-complete@0.6.5/dist/build.min.js"></script> -->

    <!-- axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>

  </head>
  <body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
    {% include "includes/nav.html" %}
    <div class="app-body">
      {% include "includes/sidebar.html" %}
      <main class="main">
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'core:dashboard' %}">Dashboard</a>
          </li>
          <!-- <li class="breadcrumb-item">
            <a href="">Admin</a>
          </li> -->
          {% block breadcrumb %}{% endblock %}
          <!-- Breadcrumb Menu-->
          <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
              <!-- <a class="btn" href="">
                <i class="icon-speech"></i>
              </a>
              <a class="btn" href="./">
                <i class="icon-graph"></i>  Dashboard</a> -->
              <!-- <a class="btn" href="">
                <i class="icon-settings"></i>  Settings</a> -->
            </div>
          </li>
        </ol>
        <div class="container-fluid">
          <div class="animated fadeIn">

            {% block content %}{% endblock content %}

          </div>

        </div>
      </main>
      {% include "includes/aside-menu.html" %}
    </div>
    {% include "includes/footer.html" %}
    <!-- Bootstrap and necessary plugins-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script> -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/jquery.maskedinput.js' %}"></script>
    <script src="{% static 'js/ui.datepicker-pt-BR.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'js/coreui.min.js' %}"></script>
    <!-- Datatable -->
    <!-- <script src="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/sl-1.2.5/datatables.min.js"></script> -->
    <!-- <script src="https://cdn.datatables.net/select/1.2.5/js/dataTables.select.min.js"></script> -->
    <!-- Plugins and scripts required by this view-->
    <!-- <script src="{% static 'js/custom-tooltips.min.js' %}"></script> -->
    <!-- <script src="{% static 'js/main.js' %}"></script> -->

    {% block js %}{% endblock %}
  </body>
</html>

backend/myproject/core/templates/configs.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  Configurações
{% endblock title %}

{% block breadcrumb %}
  {% include "includes/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}

<div class="row">
   <div class="col-md-12">
     <div class="card">
       <div class="card-header">
         Permissões dos Usuários
       </div>
       <div class="card-body">
         <div class="col-sm-6">

          <div class='row mt-3'>
            <div class="col-md-2">
              <i class="fa fa-cog fa-5x"></i>
            </div>

          <div class="col-md-10">
            <table class="table">
                  <tr>
                    <td>Usuários</td>
                    <td>Editar</td>
                  </tr>

                <tbody>
                    <tr>
                    <td>John Smith</td>
                      <td width="10" align="center">
                        <a href="{% url 'core:configs_edit' %}">
                          <i class="icon-note"></i>
                        </a>
                    </div>
                      </td>
                    </tr>
                    <tr>
                      <td>Herbert Hoover</td>
                      <td width="10" align="center">
                        <a href="{% url 'core:configs_edit' %}">
                          <i class="icon-note"></i>
                        </a>
                      </td>
                    </tr>
                </tbody>

              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
{% endblock js %}

backend/myproject/core/templates/configs_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  Configurações
{% endblock title %}

{% block breadcrumb %}
  {% include "includes/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}

<div class="row">

   <div class="col-md-12">

     <div class="card">
       <div class="card-header">
         Editando: USER1
       </div>

       <div class="card-body">
         <div class="col-sm-6">
           <div class="col-md-10">

              <form class="form table-responsive" action="" method="POST">
                <table class="col">
                  {% csrf_token %}

                   {% comment %}
                     for xxx
                   {% endcomment %}
                    <tbody>
                      <td align="center">
                        <div class="form-group">
                          <label class="switch switch-pill switch-primary">
                            <input type="checkbox" class="switch-input" checked>
                            <span class="switch-slider"></span>
                          </label>
                        </div>
                      </td>
                      <td> Adicionar usuários</td>
                    </tbody>
                    <tbody>
                      <td align="center">
                        <div class="form-group">
                          <label class="switch switch-pill switch-primary">
                            <input type="checkbox" class="switch-input">
                            <span class="switch-slider"></span>
                          </label>
                        </div>
                      </td>
                      <td> Deletar Usuários</td>
                    </tbody>
                    {% comment %}
                      endfor
                    {% endcomment %}


                </table>
                <button class="btn btn-outline-success" type="submit">Atualizar Permissões</button>
              </form>

            </div>
           </div>
         </div>

       </div>
     </div>

   </div>
 </div>


{% endblock content %}

{% block js %}
{% endblock js %}

backend/myproject/core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>CRM</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'landpage/css/bootstrap/css/theme.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'landpage/css/style.css' %}" rel="stylesheet">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
        <!-- <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700,100' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Raleway:300,700,900,500' rel='stylesheet' type='text/css'> -->
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/typicons/2.0.7/typicons.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'landpage/assets/css/pushy.css' %}">
        <link rel="stylesheet" href="{% static 'landpage/assets/css/masonry.css' %}">
        <link rel="stylesheet" href="{% static 'landpage/assets/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'landpage/assets/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'landpage/assets/css/odometer-theme-default.css' %}">
        <script>
        window.odometerOptions = {
          selector: '.odometer',
          format: '(,ddd)', // Change how digit groups are formatted, and how many digits are shown after the decimal point
          duration: 13000, // Change how long the javascript expects the CSS animation to take
          theme: 'default'
        };
        </script>
    </head>
    <body>

      {% if mydebug %}
        <!-- <div class="pull-right" style="padding: 10px 50px 0 0">
          <a href="{% url 'core:dashboard' %}" style="color:#235367">Dashboard</a>
      </div> -->
      {% endif %}
      <!-- Site Overlay -->
      <div class="site-overlay"></div>

        <header id="home">
            <div class="container-fluid">
                <!-- change the image in style.css to the class header .container-fluid [approximately row 50] -->
                <div class="container">
                    <div class="jumbotron">
                      <img src="{% static 'img/django-seeklogo.com.svg' %}" alt="django" height="300px">
                      <img src="{% static 'img/vuejs.png' %}" alt="vuejs" height="300px">
                      <p>
                        <a href="{% url 'core:dashboard' %}" style="color:#235367">Dashboard</a>
                      </p>
                    </div>
                </div>
            </div>
        </header>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'landpage/js/jquery.min.js' %}"></script>
        <script src="{% static 'landpage/js/bootstrap.min.js' %}"></script>
        <script src="https://netdna.bootstrapcdn.com/twitter-bootstrap/2.0.4/js/bootstrap-scrollspy.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="{% static 'landpage/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="http://masonry.desandro.com/masonry.pkgd.js"></script>
        <script src="{% static 'landpage/assets/js/masonry.js' %}"></script>
        <script src="{% static 'landpage/assets/js/pushy.min.js' %}"></script>
        <script src="{% static 'landpage/assets/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'landpage/assets/js/wow.min.js' %}"></script>
        <script src="{% static 'landpage/assets/js/scripts.js' %}"></script>
        <script src="{% static 'landpage/assets/js/odometer.js' %}"></script>
    </body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-34344036-1', 'auto');
  ga('send', 'pageview');

</script>