backend/myproject/core/urls.py
from django.urls import path
from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('dashboard/', v.dashboard, name='dashboard'),
    path('configs/', v.configs, name='configs'),
    path('configs/edit/', v.configs_edit, name='configs_edit'),
]

backend/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('accounts/', include('myproject.accounts.urls')),
    path('api/crm/', include('myproject.crm.urls')),
    # path('crm/', include('myproject.crm.urls')),
    path('financial/', include('myproject.financial.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

backend/myproject/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    address_number = models.IntegerField('número', null=True, blank=True)
    complement = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True


class Document(models.Model):
    cpf = models.CharField(
        'CPF',
        max_length=14,
        unique=True,
        null=True,
        blank=True
    )
    rg = models.CharField('RG', max_length=11, null=True, blank=True)
    cnh = models.CharField('CNH', max_length=20, null=True, blank=True)
    cnpj = models.CharField(
        'CNPJ',
        max_length=18,
        unique=True,
        null=True,
        blank=True
    )
    imun = models.CharField(
        'Inscrição Municipal',
        max_length=12,
        null=True,
        blank=True
    )
    ie = models.CharField(
        'Inscrição Estadual',
        max_length=12,
        null=True,
        blank=True
    )

    class Meta:
        abstract = True


class Active(models.Model):
    active = models.BooleanField('ativo', default=True)

    class Meta:
        abstract = True

backend/myproject/crm/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse, reverse_lazy
from myproject.core.models import TimeStampedModel, Address, Document, Active
from myproject.utils.lists import PHONE_TYPE, PERSON_TYPE, COMPANY_TYPE, DEPARTMENT
from .managers import (
    CompanyManager,
    EmployeeContactManager,
    EmployeePhoneManager,
    PersonManager,
    ProviderManager,
)


def gen_slug(fname, lname, email):
    fullname = '{} {}'.format(fname, lname)
    if fullname.strip():
        slug = slugify(fullname)
    else:
        slug = slugify(email)
    return slug


class People(TimeStampedModel, Address, Document, Active):
    ''' Tabela base de pessoas '''
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    personal_email = models.EmailField('E-mail pessoal', null=True, blank=True)
    slug = models.SlugField()
    photo = models.ImageField('foto', null=True, blank=True)
    birthday = models.DateField('nascimento', null=True, blank=True)
    father = models.CharField(
        'nome do pai',
        max_length=255,
        null=True,
        blank=True
    )
    mother = models.CharField(
        'nome da mãe',
        max_length=255,
        null=True,
        blank=True
    )
    info = models.TextField('informações', null=True, blank=True)

    class Meta:
        abstract = True

    def get_address(self):
        return '{}, {} {}'.format(self.address, self.address_number, self.complement or '')

    def get_address_complement(self):
        return ' - '.join(filter(None, [self.district, self.city, self.uf]))


class Person(People, User):
    person_type = models.CharField(
        'usuário ou funcionário',
        max_length=1,
        choices=PERSON_TYPE,
        default='f'
    )

    objects = PersonManager()

    def get_absolute_url(self):
        pass
        # return r('crm:person_detail', slug=self.slug)


class ContactBase(Active):
    name = models.CharField('Nome', max_length=100, null=True, blank=True)
    email = models.EmailField('E-mail', null=True, blank=True)
    phone = models.CharField('Telefone', max_length=20, null=True, blank=True)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri',
    )
    contact_or_phone = models.BooleanField(
        default=True,
        help_text='Contato ou telefone pessoal'
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class BankAccountBase(Active):
    name = models.CharField('Nome', max_length=100)
    bank = models.CharField('Banco', max_length=5, null=True, blank=True)
    agency = models.CharField('Agência', max_length=20, null=True, blank=True)
    account = models.CharField('Conta', max_length=20, null=True, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return '{}-{}-{}'.format(self.bank, self.agency, self.account)


class Company(TimeStampedModel, Address, Document, Active):
    # Razão Social
    social_name = models.CharField('razão social', max_length=100, unique=True)
    # Nome Fantasia
    name = models.CharField(
        'nome fantasia',
        max_length=100,
        null=True,
        blank=True
    )
    email = models.EmailField(null=True, blank=True)
    slug = models.SlugField(max_length=100)
    info = models.TextField('informações', null=True, blank=True)
    company_type = models.CharField(
        'cliente ou fornecedor',
        max_length=1,
        choices=COMPANY_TYPE,
        default='c'
    )

    objects = CompanyManager()

    class Meta:
        ordering = ('social_name',)
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return self.social_name

    def get_absolute_url(self):
        return reverse_lazy('crm:company_detail', kwargs={'pk': self.pk})

    def get_address(self):
        return '{}, {} {}'.format(self.address, self.address_number, self.complement or '')

    def get_address_complement(self):
        return ' - '.join(filter(None, [self.district, self.city, self.uf]))

    @property
    def list_url(self):
        return reverse('crm:company_list')

    @property
    def update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:company_update', kwargs=kw)
        return None

    @property
    def delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:company_delete', kwargs=kw)
        return None

    def save(self, *args, **kwargs):
        self.slug = gen_slug(self.social_name, self.name, self.email)
        super(Company, self).save(*args, **kwargs)

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'social_name': self.social_name,
        }


class CompanyContact(ContactBase):
    company = models.ForeignKey('Company', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Contato Empresa'
        verbose_name_plural = 'Contatos Empresas'


class Provider(Company):
    objects = ProviderManager()

    class Meta:
        proxy = True
        verbose_name = 'fornecedor'
        verbose_name_plural = 'fornecedores'

    def get_absolute_url(self):
        return reverse_lazy('crm:provider_detail', kwargs={'pk': self.pk})

    @property
    def list_url(self):
        return reverse('crm:provider_list')

    @property
    def update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:provider_update', kwargs=kw)
        return None

    @property
    def delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:provider_delete', kwargs=kw)
        return None

    def save(self, *args, **kwargs):
        self.slug = gen_slug(self.social_name, self.name, self.email)
        self.company_type = 'f'
        super(Provider, self).save(*args, **kwargs)


class ProviderContact(ContactBase):
    provider = models.ForeignKey('Provider', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Contato Fornecedor'
        verbose_name_plural = 'Contatos Fornecedores'


class Employee(People):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    internal = models.BooleanField('interno', default=True)
    occupation = models.ForeignKey(
        'Occupation',
        verbose_name='cargo',
        related_name='employee_occupation',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    date_admission = models.DateTimeField(
        'admissão',
        null=True,
        blank=True
    )
    date_release = models.DateTimeField(
        'saída',
        null=True,
        blank=True
    )
    salary = models.DecimalField(
        'salário',
        max_digits=8,
        decimal_places=2,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('user__first_name',)
        verbose_name = u'funcionário'
        verbose_name_plural = u'funcionários'

    def __str__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return reverse_lazy('crm:employee_detail', kwargs={'pk': self.pk})

    full_name = property(__str__)

    def employee_phone_first(self):
        return EmployeePhone.objects.filter(employee=self, active=True, phone_type='pri').first()

    @property
    def list_url(self):
        return reverse('crm:employee_list')

    @property
    def update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:employee_update', kwargs=kw)
        return None

    @property
    def delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:employee_delete', kwargs=kw)
        return None

    # def save(self, *args, **kwargs):
    #     # Salva username = email
    #     self.username = self.email
    #     # self.slug = gen_slug(self.first_name, self.last_name, self.email)
    #     super(Employee, self).save(*args, **kwargs)

    def to_dict_json(self):
        _name = (self.user.first_name, self.user.last_name)
        return {
            'pk': self.pk,
            'name': '{} {}'.format(_name[0], _name[1]),
        }


# @receiver(post_save, sender=Employee)
# def create_or_update_employee(sender, instance, created, **kwargs):
#     if created:
#         # Add Group
#         simpleuser, _ = Group.objects.get_or_create(name='simpleuser')
#         instance.groups.add(simpleuser)


class EmployeeContact(ContactBase):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)

    objects = EmployeeContactManager()

    class Meta:
        verbose_name = 'Contato Funcionário'
        verbose_name_plural = 'Contatos Funcionários'


class EmployeePhone(EmployeeContact):
    objects = EmployeePhoneManager()

    class Meta:
        proxy = True
        verbose_name = 'Telefone Funcionário'
        verbose_name_plural = 'Telefones Funcionários'

    def __str__(self):
        return self.phone


class EmployeeBankAccount(BankAccountBase):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Conta do Funcionário'
        verbose_name_plural = 'Contas dos Funcionários'


class Occupation(models.Model):
    occupation = models.CharField('cargo', max_length=50, unique=True)
    department = models.CharField(
        'departamento',
        max_length=3,
        choices=DEPARTMENT,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('occupation',)
        verbose_name = 'cargo'
        verbose_name_plural = 'cargos'

    def __str__(self):
        return self.occupation

backend/myproject/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    ctx = {'mydebug': True}
    return render(request, 'index.html', ctx)


def dashboard(request):
    return render(request, 'dashboard.html')


@login_required
def configs(request):
    return render(request, 'configs.html')


@login_required
def configs_edit(request):
    return render(request, 'configs_edit.html')

backend/myproject/core/templates/modal/modal_bank_add.html
<!-- modalBankAccountAdd -->
<div class="modal fade" id="modalBankAccountAdd" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Adicionar Conta
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_bank_name">Nome</label>
            <input id="id_bank_name" name="bank_name" v-model="bank_name" type="text" class="form-control" />
          </div>
          <div class="form-group">
            <label for="id_bank">Banco</label>
            <input id="id_bank" name="bank" v-model="bank" type="text" class="form-control" maxlength="5" />
          </div>
          <div class="form-group">
            <label for="id_agency">Agência</label>
            <input id="id_agency" name="agency" v-model="agency" type="text" class="form-control" maxlength="20" />
          </div>
          <div class="form-group">
            <label for="id_account">Conta</label>
            <input id="id_account" name="account" v-model="account" type="text" class="form-control" maxlength="20" />
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
          <button type="submit" class="btn btn-primary" @click="save_bank()" data-dismiss="modal">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/myproject/core/templates/modal/modal_bank_edit.html
<!-- modalBankAccountEdit -->
<div class="modal fade" id="modalBankAccountEdit" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Editar Conta
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          {% csrf_token %}
          <input id="" name="" type="hidden" v-model="bank_pk"/>
          <div class="form-group">
            <label for="id_bank_name">Nome</label>
            <input id="id_bank_name" name="bank_name" v-model="bank_name" type="text" class="form-control" />
          </div>
          <div class="form-group">
            <label for="id_bank">Banco</label>
            <input id="id_bank" name="bank" v-model="bank" type="text" class="form-control" maxlength="5" />
          </div>
          <div class="form-group">
            <label for="id_agency">Agência</label>
            <input id="id_agency" name="agency" v-model="agency" type="text" class="form-control" maxlength="20" />
          </div>
          <div class="form-group">
            <label for="id_account">Conta</label>
            <input id="id_account" name="account" v-model="account" type="text" class="form-control" maxlength="20" />
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
          <button type="submit" class="btn btn-primary" @click="edit_bank()" data-dismiss="modal">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/myproject/core/templates/modal/modal_contact_add.html
<!-- modalContactAdd -->
<div class="modal fade" id="modalContactAdd" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Adicionar Contato
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          {% csrf_token %}
            <!-- { for field in form.visible_fields %}
              <div class="form-group">
                <label for="{ field.id_for_label }}">{ field.label }}</label>
                { render_field field class="form-control" %}
                { for error in field.errors %}
                  <span class="text-muted">{ error }}</span>
                { endfor %}
              </div>
            { endfor %} -->
          <div class="form-group">
            <label for="id_name">Nome</label>
            <input id="id_name" name="name" v-model="name" type="text" class="form-control" maxlength="100" />
          </div>
          <div class="form-group">
            <label for="id_email">E-Mail</label>
            <input id="id_email" name="email" v-model="email" type="email" class="form-control" maxlength="254" />
          </div>
          <div class="form-group">
            <label for="id_phone">Telefone</label>
            <input id="id_phone" name="phone" v-model="phone" type="text" class="form-control" maxlength="20" />
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
          <button type="submit" class="btn btn-primary" @click="save_contact()" data-dismiss="modal">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/myproject/core/templates/modal/modal_contact_edit.html
<!-- modalContactEdit -->
<div class="modal fade" id="modalContactEdit" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Editar Contato
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          {% csrf_token %}
          <input id="" name="" type="hidden" v-model="pk"/>
          <div class="form-group">
            <label for="id_name">Nome</label>
            <input id="id_name" name="name" v-model="name" type="text" class="form-control" maxlength="100" />
          </div>
          <div class="form-group">
            <label for="id_email">E-Mail</label>
            <input id="id_email" name="email" v-model="email" type="email" class="form-control" maxlength="254" />
          </div>
          <div class="form-group">
            <label for="id_phone">Telefone</label>
            <input id="id_phone" name="phone" v-model="phone" type="text" class="form-control" maxlength="20" />
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
          <button type="submit" class="btn btn-primary" @click="edit_contact()" data-dismiss="modal">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/myproject/core/templates/modal/modal_delete.html
<!-- ModalDelete -->
<div class="modal fade" id="ModalDelete" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Deletar
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <div class="modal-body">
          Deseja deletar <span id="span-modal">{{ object }}</span>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          Fechar
        </button>
        <a id="a-modal" href="{{ object.delete_url }}">
          <button type="button" class="btn btn-danger">
            Deletar
          </button>
        </a>
      </div>
    </div>
  </div>
</div>

backend/myproject/core/templates/modal/modal_phone_add.html
<!-- modalPhoneAdd -->
<div class="modal fade" id="modalPhoneAdd" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Adicionar Telefone
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_phone">Telefone</label>
            <input id="id_phone" name="phone" v-model="phone2" type="text" class="form-control" maxlength="20" />
          </div>
          <div class="form-group">
            <label for="id_phone_type">Tipo</label>
            <select id="id_phone_type" name="phone_type" class="form-control" v-model="phone_type">
              <option v-for="phone_type in phone_types" :value="phone_type.value">
                ${ phone_type.text }
              </option>
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
          <button type="submit" class="btn btn-primary" @click="save_phone()" data-dismiss="modal">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

backend/myproject/core/templates/modal/modal_phone_edit.html
<!-- modalPhoneEdit -->
<div class="modal fade" id="modalPhoneEdit" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">
          Editar Telefone
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          {% csrf_token %}
          <input id="" name="" type="hidden" v-model="pk"/>
          <div class="form-group">
            <label for="id_phone">Telefone</label>
            <input id="id_phone" name="phone" v-model="phone2" type="text" class="form-control" maxlength="20" />
          </div>
          <div class="form-group">
            <label for="id_phone_type">Tipo</label>
            <select id="id_phone_type" name="phone_type" class="form-control" v-model="phone_type">
              <option v-for="phone_type in phone_types" :value="phone_type.value">
                ${ phone_type.text }
              </option>
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
          <button type="submit" class="btn btn-primary" @click="edit_phone()" data-dismiss="modal">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>